name: Continuos Integration

on:
  pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.0"

      - name: Install dependencies
        run: npm install
        working-directory: ./

      # - name: Run linter
      #   run: npm run lint
      #   working-directory: ./

      - name: Run unit tests
        run: npm run test:cov
        working-directory: ./

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/index.html

      - name: Run build
        run: npm run build
        working-directory: ./
